services:
    # ServerProvider
    kraken.ws.server_provider:
        class: "%kraken_collective.ws_symfony.server_provider%"
        calls:
            - ["setContainer", ["@service_container"]]

    # Loop Models
    kraken.ws.loop_model.select_loop:
        class: "%kraken_collective.ws_symfony.select_loop%"
        public: false
        tags:
            - { name: kraken.loop_model, alias: select_loop }

    # Default Component
    kraken.ws.network_component.default:
        class: KrakenCollective\WsSymfonyBundle\Server\ServerDefaultComponent
        public: false
        arguments:
            - "@event_dispatcher"

    # Misc
    kraken.ws.connection_helper:
        class: KrakenCollective\WsSymfonyBundle\Helper\ConnectionHelper
